# Site settings
title: Unfiltered Reality
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Unfiltered Reality Podcast - Exploring the truth behind popular topics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lopdabop.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  LopDaBop

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
